### ISSUE TITLE
Command line utility?

### ISSUE THREAD

**Issue by alexanderGugel** [dherman/asm.js#101]
I created this simple command line utility for validating asm code: https://github.com/alexanderGugel/validate-asm

It seems like people like it, but it's essentially only wrapping your code into a command line utility. I think it would make more sense to put this right into this repo. I'm more than happy to put together a PR if there's interest.

**Comment by sunfishcode** [comment]
I think it would make sense to put this into the main repo too. Please do file a PR. Thanks!
