### ISSUE TITLE
Math.round not supported

### ISSUE THREAD

**Issue by sbalko** [dherman/asm.js#84]
I noticed that Math.round is not currently supported by the asm.js specification (or its implementation in Firefox, for that matter). 

While I am not sure if there is any particular reason for this, I would love to have it included. Emscripten uses Math.round to implement standard library functions such as rint and others. As Math.round is not currently asm.js compliant, this lets Ionmonkey break out from asm.js mode for every Math.round call, with accompanying performance penalties (also see here: https://groups.google.com/forum/m/?fromgroups#!topic/emscripten-discuss/Cgdd3RUsLME) 

Any chance to have Math.round added?

Soeren

**Comment by sunfishcode** [comment]
The general way forward is to implement math functions in C code which can be compiled to asm.js by Emscripten. This now includes rint and many others, so there's no longer a major need for Math.round in asm.js. With that, and its non-standard rounding behavior, it doesn't look like it'll make sense.
