### ISSUE TITLE
`if` fails the validator: `types` does not exist

### ISSUE THREAD

**Issue by amadanmath** [dherman/asm.js#86]
If the code includes an `if`, the validator errors out, due to this line in `Vp.ifStatement`:

    this.checkSubtype(this.expression(test), types.boolish, "if test", test.loc);

The variable `types` does not exist. I believe one wants `ty` instead; and `ty` does not contain `boolish` nor `Boolish`. It was probably missed in 182e4b9efe556f205e33be1f9357938a41ebbbe3 and should be `ty.Intish`?

**Comment by soliton4** [comment]
@amadanmath 
fixed it:

https://github.com/dherman/asm.js/pull/96

**Comment by sunfishcode** [comment]
The fix is merged.
