### ISSUE TITLE
is this repository maintained?

### ISSUE THREAD

**Issue by soliton4** [dherman/asm.js#99]
if so nevermind (no pressure)

if not, can someone point me to a maintained asm.js validator?

thank you

**Comment by kripken** [comment]
The main people who are involved here are generally pretty busy (one almost all the time, the other just around now).

This is the best validator I am aware of.

**Comment by soliton4** [comment]
thx for coming back to me
can i assume the pull requests are gonna be reviewed / merged?

thx

**Comment by sunfishcode** [comment]
The other notable validator implementation today is OdinMonkey, which is built into Firefox (see the console for diagnostics) and the SpiderMonkey standalone js shell (use the -w command-line flag).

The validator code here is unfortunately not being actively developed right now, and is likely to be out of date in various areas. I'm happy to review and merge patches to fix it though, if anyone wants to help. As Alon mentioned, I am quite busy right now, and may not respond right away, but I will try to review and merge pull requests when I can.

**Comment by sunfishcode** [comment]
The pull requests have been reviewed and merged.
